# Generated by Django 4.2 on 2024-07-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-created"]},
        ),
    ]
