# Generated by Django 4.2 on 2024-07-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0002_alter_collection_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SWPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("birth_year", models.CharField()),
                ("homeworld", models.CharField()),
                ("height", models.CharField()),
                ("mass", models.CharField()),
                ("hair_color", models.CharField()),
                ("skin_color", models.CharField()),
                ("eye_color", models.CharField()),
                ("gender", models.CharField()),
                ("date", models.DateField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="data_collections.collection",
                    ),
                ),
            ],
        ),
    ]
