# Generated by Django 4.2 on 2024-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collections", "0003_swperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="file",
            field=models.FileField(max_length=64, upload_to=""),
        ),
    ]
